### ISSUE TITLE
Can't disable copy of scripts and include

### ISSUE THREAD

**Issue by rtxa** [Hedgefog/node-amxxpack#10]
Hi Mr. Hedgefog, thanks a lot for the new features and for having adressed some the issues I have posted, I didn't have the time to test them because I wasn't into AMXX development anymore by that time.

Removing or leaving empty the variables `scripts` or `include` on the `output` section will not disable the copying of these files on the `dist` default folder.

My proposed solution will be the same as in #3, when the string is empty `''` or not provided in the file, then disable the copying.

The feature is useful if you're just planning on only distributing compiled binaries, or you're just using the hot-reload feature (my case).

**Comment by hedgefog** [comment]
Make sure you are using the latest version.

Scripts output is optional: https://github.com/Hedgefog/node-amxxpack/blob/964547c4258c1abaec90318c19d0a57dfcb64e8d/src/builder/builder.ts#L157

What about include output, I'll make it optional in a future update.

**Comment by rtxa** [comment]
According to `amxxpack --version`, I'm using version `1.3.3` which I downloaded from npm.

And my .amxxpack.json looks like this:

```json
{
  "input": {
    "scripts": "./valve/addons/amxmodx/scripting",
    "include": "./valve/addons/amxmodx/scripting/include",
    "assets": [
      {
        "dir": "./valve",
        "filter": "*.!(so)"
      }
    ]
  },
  "output": {
    "plugins": "C:/Users/rtxa/Documents/Servidores HL/AG Mod X/valve/addons/amxmodx/plugins",
    "assets": "C:/Users/rtxa/Documents/Servidores HL/AG Mod X/valve",
    "scripts": "",
    "include": ""
  },
  "compiler": {
    "dir": "./.compiler",
    "version": "1.10",
    "executable": "amxxpc"
  },
  "thirdparty": {
    "dir": "./.thirdparty",
    "dependencies": []
  },
  "include": [],
  "rules": {
    "flatCompilation": true
  } 
}
```
And the log:

```
[INFO] Plugin updated: C:/Users/rtxa/Documents/Servidores HL/AG Mod X/valve/addons/amxmodx/plugins/agmodx.amxx
[INFO] Script updated: C:/Users/rtxa/Documents/GitHub/agmodx/dist/addons/amxmodx/scripting/agmodx.sma
```
I'm also using this with `amxxpack build --watch`

**Comment by rtxa** [comment]
PD: When it's set to an empty string, it's copied in the project folder, which will be `C:/Users/rtxa/Documents/GitHub/agmodx/`, and not in the `dist` folder.

When the variable is just removed, then it gets copied to the default directory which is the `dist` folder: `C:/Users/rtxa/Documents/GitHub/agmodx/dist`.

**Comment by hedgefog** [comment]
Ok, that makes sense. I'll investigate and fix it.

**Comment by Hedgefog** [comment]
Thanks for your report! Fixed in version 1.4.0.

**Comment by hedgefog** [comment]
Thanks for your report! Fixed in version 1.4.1.

**Comment by rtxa** [comment]
It's been a while since you released the new version but I just stopped coding for HL in that time. I'm testing with version 1.4.4 and unfortunately the issue is still not fixed, not sure what are the changes you made but using an empty string on `scripts` and `include` isn't disabling the copy but instead copying the files in the base folder "C:/Users/rtxa/Documents/GitHub/agmodx/".

**Comment by hedgefog** [comment]
> It's been a while since you released the new version but I just stopped coding for HL in that time. I'm testing with version 1.4.4 and unfortunately the issue is still not fixed, not sure what are the changes you made but using an empty string on `scripts` and `include` isn't disabling the copy but instead copying the files in the base folder "C:/Users/rtxa/Documents/GitHub/agmodx/".

Use `null` value instead of an empty string 😉
Strings values always mean a path, in the case of an empty string, the path is relative to project dir.

https://github.com/Hedgefog/node-amxxpack/blob/93206d5615ae8bfd1547ff5b4ffd862862516a3b/src/project-config/resolve.ts#L17

https://github.com/Hedgefog/node-amxxpack/blob/93206d5615ae8bfd1547ff5b4ffd862862516a3b/src/builder/builder.ts#L193

https://github.com/Hedgefog/node-amxxpack/blob/93206d5615ae8bfd1547ff5b4ffd862862516a3b/tests/project-config/resolver.test.ts#L33

**Comment by rtxa** [comment]
Thanks, but because the change doesn't mention how the option is disabled I though that was the way without taking a look into the code. Anyway, it should be documented in the README.md to avoid any confusions.

**Comment by hedgefog** [comment]
Yep, that makes sense. Updated!
